### ISSUE TITLE
wrong path when using requirejs

### ISSUE THREAD

**Issue by pharacyde** [webjars/proj4js#2]
The current released webjar for Proj4 ("org.webjars" % "proj4js" % "2.2.1") contains the wrong requirejs path. It points to 'http://localhost:8080/webjars/proj4js/2.2.1/proj4js.js' instead of 'http://localhost:8080/webjars/proj4js/2.2.1/proj4.js'.   The change is already done, I believe a new release would be enough.

**Comment by jamesward** [comment]
A fix is being released shortly as `2.2.1-1`.
